### ISSUE TITLE
Criticism

### ISSUE THREAD

**Issue by MagesRL** [nordicgaming/ladder#14]
It appears there is not enough documentation in order for me to successfully base my rocketleague api on this. Please add support for the gibson marketplace.

**Comment by chriskolenko** [comment]
Thank you for your interest in accessing our API! Our API is currently in closed beta. To request API access, please email RLPublicAPI@psyonix.com and we will get back to you as soon as we can. All requests are reviewed and access is granted on a case-by-case basis.
